# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
before_install:
  - sudo apt-get install cppcheck
before_install2:
  - sudo apt-get install cppcheck
script:
  - make
#  - make test
